posts/forms.py
from wtforms import  Form, StringField, TextAreaField, validators

class PostForm(Form):
    title = StringField('Title', validators=[
        validators.DataRequired()
    ])
    body = TextAreaField('Body', validators=[
        validators.DataRequired()
    ])
    #tags = StringField('Tags')

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask_login import current_user
from models import Post, Tag, User

from flask import request
from .forms import PostForm

from app import db
from flask import redirect, url_for

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods={'POST', 'GET'})
@login_required
def create_post():
    form = PostForm(request.form)
    if request.method == 'POST' and form.validate():
        title = request.form['title']
        body = request.form['body']
        #tags = request.form['tags']
        try:
            post = Post(title=title, body=body)
            post.authors.append(current_user)
            #tag = Tag(name=tags)
            #db.session.add(tag)
            #db.session.commit()
            #post.tags.append(tag)
            #add_tags_to_post(post, parse_tags(tags))
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wrong!')

        return redirect(url_for('posts.index'))

    return render_template('posts/create_post.html', form=form)

'''
def parse_tags(tag_string):
    tags_slugs = tag_string.split(' ')
    return [Tag(name=tag) for tag in tags_slugs]

def add_tags_to_post(post, tags):
    for tag in tags:
        post.tags.append(tag)
'''

@posts.route('/')
def index():
    #Поиск
    q = request.args.get('q')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
        print(posts)
    else:
        posts = Post.query.order_by(Post.timestamp.desc())
        print(posts)

    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', posts=posts, pages=pages)


#TODO slug + id - для полной уникальности
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

@posts.route('/author/posts/<id>')
def author_detail(id):
    posts = Post.query.join(User.posts).filter(User.id == id)
    print(posts)
    author = User.query.get(id)
    return render_template('posts/authors_detail.html', posts=posts, author=author)


@posts.route('/<slug>/edit/', methods=['POST','GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    print(post.authrs)
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)

posts/templates/posts/authors_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ author.nickname }}
{% endblock %}

{% block content_title %}
    Posts for "{{ author.nickname }}" author:
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug = post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}
{% endblock %}

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}


    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}

                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>

            {% endfor %}
            <button type="submit" class="btn btn-success">Create</button>

        </form>
    </div>
    

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}


    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Change</button>

        </form>
    </div>
    

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    <h1>
    Articles:
    </h1>
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <!-- Генерация ссылки-->
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }} </a>
        </p>
    {% endfor %}

    <nav>
        <ul class="pagination">
            <li {% if not pages.has_prev %} class="page-item disabled"{% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1">Previous</a></li>

            {% for page in pages.iter_pages() %}
                <li {% if page == pages.page %}class="page-item active" {% endif %}>
                    <a class="page-link" href="./?page={{ page }}">{{ page }}<span class="sr-only">(current)</span></a></li>
            {% endfor %}

            <li class="page-item"><a class="page-link" href="./?page={{ pages.next_num }}">Next</a></li>
        </ul>
    </nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    <h1>
        {{ post.title }}
    </h1>

{% endblock %}

{% block content %}
    <div class="tags">

    {% for tag in tags %}
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
            <span class="badge badge-light">{{ tag.name }}</span>
        </a>
    {% endfor %}
    </div>
    <div class="col-md-offset-3 col-md-6">
    {{ post.body }}
    </div>
    {% for author in post.authors %}
        <a href="{{ url_for('posts.author_detail', id=author.id) }}">
            <span class="badge badge-light">{{ author.nickname }}</span>
        </a>
    {% endfor %}
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content_title %}
    Articles for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug = post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}
{% endblock %}